In [1]:
import pandas as pd 
import numpy as np
df=pd.read_csv(r'C:\Users\Indhira Durai\OneDrive\Documents\GitHub\Uber-Eats-GUVI\Data\Raw\Uber_Eats_data.csv')
df.head(2)

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari

In [2]:
print(f"shapes:{df.shape}")
df.info()

shapes:(23193, 13)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23193 entries, 0 to 23192
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         23193 non-null  object
 1   online_order                 23193 non-null  object
 2   book_table                   23193 non-null  object
 3   rate                         23193 non-null  object
 4   votes                        23193 non-null  int64
 5   phone                        23193 non-null  object
 6   location                     23193 non-null  object
 7   rest_type                    23193 non-null  object
 8   dish_liked                   23193 non-null  object
 9   cuisines                     23193 non-null  object
 10  approx_cost(for two people)  23193 non-null  object
 11  listed_in(type)              23193 non-null  object
 12  listed_in(city)              23193 non-null  object
dtypes: int64(1), object(12)
memory usage: 2.3+ MB

In [3]:
print(df['rate'].unique())
print(df['approx_cost(for two people)'].unique())

['4.1/5' '3.8/5' '3.7/5' '4.6/5' '4.0/5' '4.2/5' '3.9/5' '3.0/5' '3.6/5'
 '2.8/5' '4.4/5' '3.1/5' '4.3/5' '2.6/5' '3.3/5' '3.5/5' '3.8 /5' '3.2/5'
 '4.5/5' '2.5/5' '2.9/5' '3.4/5' '2.7/5' '4.7/5' 'NEW' '2.4/5' '2.2/5'
 '2.3/5' '4.8/5' '3.9 /5' '4.2 /5' '4.0 /5' '4.1 /5' '2.9 /5' '2.7 /5'
 '2.5 /5' '2.6 /5' '4.5 /5' '4.3 /5' '3.7 /5' '4.4 /5' '4.9/5' '2.1/5'
 '2.0/5' '1.8/5' '3.4 /5' '3.6 /5' '3.3 /5' '4.6 /5' '4.9 /5' '3.2 /5'
 '3.0 /5' '2.8 /5' '3.5 /5' '3.1 /5' '4.8 /5' '2.3 /5' '4.7 /5' '2.4 /5'
 '2.1 /5' '2.2 /5' '2.0 /5' '1.8 /5']
['800' '300' '600' '700' '550' '500' '450' '650' '400' '750' '200' '850'
 '1,200' '150' '350' '250' '1,500' '1,300' '1,000' '100' '900' '1,100'
 '1,600' '950' '230' '1,700' '1,400' '1,350' '2,200' '2,000' '1,800'
 '1,900' '180' '330' '2,500' '2,100' '3,000' '2,800' '3,400' '40' '1,250'
 '3,500' '4,000' '2,400' '1,450' '3,200' '6,000' '1,050' '4,100' '2,300'
 '120' '2,600' '5,000' '3,700' '1,650' '2,700' '4,500']

In [4]:
df['rate'] = df['rate'].astype(str).str.replace('/5','').str.strip()
df['rate'] = df['rate'].replace('NEW',np.nan)
df['rate'] = pd.to_numeric(df['rate'],errors='coerce')
df['rate'].describe()

count    23046.000000
mean         3.904383
std          0.426365
min          1.800000
25%          3.800000
50%          4.000000
75%          4.200000
max          4.900000
Name: rate, dtype: float64

In [5]:
print(df['rate'].unique())

[4.1 3.8 3.7 4.6 4.  4.2 3.9 3.  3.6 2.8 4.4 3.1 4.3 2.6 3.3 3.5 3.2 4.5
 2.5 2.9 3.4 2.7 4.7 nan 2.4 2.2 2.3 4.8 4.9 2.1 2.  1.8]

In [6]:
df.rename(columns={'approx_cost(for two people)':'cost'},inplace=True)
df['cost']=df['cost'].astype(str).str.replace(',','')
df['cost']=pd.to_numeric(df['cost'],errors='coerce')
df['cost'].describe()

count    23193.000000
mean       755.904368
std        521.448320
min         40.000000
25%        400.000000
50%        600.000000
75%       1000.000000
max       6000.000000
Name: cost, dtype: float64

In [7]:
print(df['cost'].unique())

[ 800  300  600  700  550  500  450  650  400  750  200  850 1200  150
  350  250 1500 1300 1000  100  900 1100 1600  950  230 1700 1400 1350
 2200 2000 1800 1900  180  330 2500 2100 3000 2800 3400   40 1250 3500
 4000 2400 1450 3200 6000 1050 4100 2300  120 2600 5000 3700 1650 2700
 4500]

In [11]:
before = len(df)
df.dropna(subset=['rate','cost','location','cuisines'], inplace=True)
after = len(df)
print(f"Before:{before}")
print(f"after:{after}")
print(f"Dropped:{before-after}")

Before:23193
after:23046
Dropped:147

In [12]:
before = len(df)
df.drop_duplicates(inplace=True)
after =  len(df)
print(f"Before:{before}")
print(f"After:{after}")
print(f"Dropped:{before-after}")

Before:23046
After:23012
Dropped:34

In [ ]:
df.rename(columns={'listed_in(type)':'listed_type','listed_in(city)':'listed_city'}, inplace=True)
print(df.columns.tolist())

['name', 'online_order', 'book_table', 'rate', 'votes', 'phone', 'location', 'rest_type', 'dish_liked', 'cuisines', 'cost', 'listed_type', 'listed_city']

In [16]:
df['price_segment']=pd.cut(df['cost'],bins=[0,300,700,100000],labels=['Low','Medium','Premium'])

In [17]:
df['price_segment'].unique()

['Premium', 'Low', 'Medium']
Categories (3, object): ['Low' < 'Medium' < 'Premium']

In [18]:
def rate_cat(r):
    if r >= 4.0:
        return 'Excellent'
    elif r >= 3.0:
        return 'Good'
    else:
        return 'Poor'
    
df['rating_category']=df['rate'].apply(rate_cat)
print(df['rating_category'].value_counts())

rating_category
Excellent    11723
Good         10116
Poor          1173
Name: count, dtype: int64

In [20]:
print(df['rating_category'].dtype)

object

In [22]:
print(f"final shape: {df.shape}")
print(df.dtypes)
df.head()

final shape: (23012, 15)
name                 object
online_order         object
book_table           object
rate                float64
votes                 int64
phone                object
location             object
rest_type            object
dish_liked           object
cuisines             object
cost                  int64
listed_type          object
listed_city          object
price_segment      category
rating_category      object
dtype: object

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,cost,listed_type,listed_city,price_segment,rating_category
0,Jalsa,Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari,Premium,Excellent
1,Spice Elephant,Yes,No,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari,Premium,Excellent
2,San Churro Cafe,Yes,No,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari,Premium,Good
3,Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari,Low,Good
4,Grand Village,No,No,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari,Medium,Good

Cleaned rate
Cleaned cost
Hnadled Nulls
Removed Duplicates
Renamed columns
Price Segment Featured
Rating Category featured

In [23]:
import os
os.makedirs('../data/clean', exist_ok=True)

df.to_csv('../data/clean/restaurants_clean.csv', index=False)

print("Saved successfully!")

Saved successfully!